import React,{useState} from 'react';
import { makeStyles } from '@material-ui/core/styles';
import Paper from '@material-ui/core/Paper';
import TextField from '@material-ui/core/TextField';
import Typography from '@material-ui/core/Typography';
import Grid from '@material-ui/core/Grid';
import Radio from '@material-ui/core/Radio';
import RadioGroup from '@material-ui/core/RadioGroup';
import FormControlLabel from '@material-ui/core/FormControlLabel';
import FormControl from '@material-ui/core/FormControl';
import FormHelperText from '@material-ui/core/FormHelperText';
import FormLabel from '@material-ui/core/FormLabel';
import Button from '@material-ui/core/Button';
import Select from './Select';
import Container from '@material-ui/core/Container';
import CssBaseline from '@material-ui/core/CssBaseline';
import { useForm, Controller } from "react-hook-form";
import {Link,useHistory} from "react-router-dom";
import {useStateMachine} from "little-state-machine";
import updateAction from './updateAction';
import axios from 'axios';

const useStyles = makeStyles((theme) => ({
  root: {
    flexWrap: 'wrap',
    '& > *': {
       margin: theme.spacing(2),
       height: theme.spacing(100),
    },
    '& .MuiTextField-root': {
        margin: theme.spacing(1),
        width:'100%',
    },
  },
  formControl: {
    margin: theme.spacing(3),
  },
  form: {
    width: '100%', // Fix IE 11 issue.
    marginTop: theme.spacing(2),
    marginLeft: theme.spacing(2),
    marginRight: theme.spacing(2),
  },
}));
const defaultValues = {
  VerboseStats: "yes",
  R8OutputCFG: "no",
  ShrinkedClassesStats:"no",
  RemoveCommonWarnings:"no",
};
const Diagnostics = (props) => {
  const classes = useStyles();
  const {state,action} = useStateMachine(updateAction);
  const [resData,setResData] = useState({"first" : 1});
  const [reqData,setReqData] = useState(state.setupDetails);
  const {handleSubmit, errors, register, control} = useForm({
    defaultValues
  });
  const [gradleConfig, setGradleConfig] = useState("loading...");
  const [gradleProperties, setGradleProperties] = useState("loading...");
  const [rulesPro, setRulesPro] = useState("loading...");
  const history = useHistory();
  const onSubmit = data => {
    action(data);
    // setReqData(state.setupDetails);
    // axios.post('http://localhost:5000/submit_form',reqData)
    //   .then(async (resData)=>{
    //       await setResData(resData)
    //   });
    // setGradleConfig(resData.gradleConfig);
    // setGradleProperties(resData.gradleProperties);
    // setRulesPro(resData.rulesPro);
    // console.log(state.setupDetails);
    // console.log(resData);
    history.push("/result");
  };
  return (
    <Container component="main" maxWidth="md" fixed={true}>
    <CssBaseline />
      <div className={classes.root}>
        <Paper elevation={1}>
          <Grid container spacing={2}>
          <br />
              <Grid item xs={24} sm={12}>
                  <Typography variant="h5">Part 4 Print Diagnostics Setup</Typography>
              </Grid>
              <Grid item xs={24} sm={12} alignContent="flex-start" alignItems='flex-start'>
                <form onSubmit={handleSubmit} class={classes.form}>
                  <section>
                    <label>Do you want stats related to obfuscation?</label>
                    <Controller
                      as={
                        <RadioGroup aria-label="verboseStats">
                          <FormControlLabel
                            value="yes"
                            control={<Radio />}
                            label="Yes"
                          />
                          <FormControlLabel
                            value="no"
                            control={<Radio />}
                            label="No"
                          />
                        </RadioGroup>
                      }
                      name="VerboseStats"
                      control={control}
                      ref = {register}
                    />
                  </section>
                  <section>
                    <label>Do you want to view the final configuration generated by R8 after build?</label>
                    <Controller
                      as={
                        <RadioGroup aria-label="r8OutputCFG">
                          <FormControlLabel
                            value="yes"
                            control={<Radio />}
                            label="Yes"
                          />
                          <FormControlLabel
                            value="no"
                            control={<Radio />}
                            label="No"
                          />
                        </RadioGroup>
                      }
                      name="R8OutputCFG"
                      control={control}
                      ref = {register}
                    />
                  </section>
                  <section>
                    <label>Do you want to view classes which were removed during shrinking?</label>
                    <Controller
                      as={
                        <RadioGroup aria-label="shrinkedClassesStats">
                          <FormControlLabel
                            value="yes"
                            control={<Radio />}
                            label="Yes"
                          />
                          <FormControlLabel
                            value="no"
                            control={<Radio />}
                            label="No"
                          />
                        </RadioGroup>
                      }
                      name="ShrinkedClassesStats"
                      control={control}
                      ref = {register}
                    />
                  </section>
                  <section>
                    <label>Do you have JavaScript enabled Webviews, Want to whitelist them from R8?</label>
                    <Controller
                      as={
                        <RadioGroup aria-label="webViewRule">
                          <FormControlLabel
                            value="yes"
                            control={<Radio />}
                            label="Yes"
                          />
                          <FormControlLabel
                            value="no"
                            control={<Radio />}
                            label="No"
                          />
                        </RadioGroup>
                      }
                      name="WebviewRule"
                      control={control}
                      ref = {register}
                    />
                  </section>
                </form>
              </Grid>
              <Grid item xs={24} sm={12}>
                <Link to="/annotationsAndPackages">
                  <Button
                    type="submit"
                    variant="contained"
                    color="secondary"
                  >Back
                  </Button>
                </Link>
                <Button
                  type="submit"
                  variant="contained"
                  color="secondary"
                  onClick={handleSubmit(onSubmit)}
                >Next
                </Button>
            </Grid>
          </Grid>
        </Paper>
      </div>
    </Container>
  );
}
export default Diagnostics;
